### ISSUE TITLE
Polymer/font-roboto^0.5.6 is not a valid repository name

### ISSUE THREAD

**Issue by schnie** [expandjs/expandjs#2]
Hey, just did a bower install to grab the latest and keep getting this error from bower `Polymer/font-roboto^0.5.6 is not a valid repository name`.  It looks like that release exists in polymers repos.. so that's kind of weird, although there is a deprecation notice.  Looks like its moving to https://github.com/PolymerElements/font-roboto.  Still not sure why the error is happening though.  Any ideas?

**Comment by Pupix** [comment]
Ooops! It was a typo, the hashtag was missing. should have been 'Polymer/font-roboto**#**^0.5.6'

Fixed.
